import "./globals.css";
import { Metadata } from "next";
import MainLayout from "./components/MainLayout";
export const metadata: Metadata = {
  title: "sanraj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <MainLayout >
      {children}
    </MainLayout>
  );
}
